site_name: VPN Proxy Agent Docs
nav:
  - Home: index.md
  - Repository Overview: about.md
  - MkDocs Tutorial: mkdocs_tutorial.md
  - Material for MkDocs: material_for_mkdocs.md
  - PR Workflow Guidance: pr_workflow.md
  - Shell Script Quality Procedure: shell_script_quality.md
docs_dir: docs
theme:
  name: readthedocs
